"""Add style_presets table

Revision ID: 09348e9a293d
Revises: f0bc7ece94d9
Create Date: 2025-12-04 19:43:26.800282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09348e9a293d'
down_revision: Union[str, None] = 'f0bc7ece94d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
